# Generated by Django 5.2.4 on 2025-08-02 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "chinese_keywords",
                    models.CharField(
                        blank=True,
                        help_text="逗号分隔的中文名称、别名或关键词",
                        max_length=255,
                    ),
                ),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("market_cap", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "eps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "listed_date",
                    models.DateField(blank=True, help_text="上市日期", null=True),
                ),
                (
                    "delisted_date",
                    models.DateField(blank=True, help_text="退市日期", null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="是否在市")),
                (
                    "financial_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "market_category",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("test_issue", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "query_count",
                    models.PositiveIntegerField(
                        db_index=True, default=0, help_text="总查询次数"
                    ),
                ),
                (
                    "last_queried",
                    models.DateTimeField(
                        blank=True, help_text="最后查询时间", null=True
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "is_active"],
                        name="stocks_stoc_ticker_e6859e_idx",
                    ),
                    models.Index(
                        fields=["-query_count", "is_active"],
                        name="stocks_stoc_query_c_a7722b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TempPriceCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=10)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_date"], name="stocks_temp_created_e84329_idx"
                    ),
                    models.Index(
                        fields=["ticker", "created_date"],
                        name="stocks_temp_ticker_2a4175_idx",
                    ),
                ],
                "unique_together": {("ticker", "created_date")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "open",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("close", models.DecimalField(decimal_places=2, max_digits=10)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["stock", "-date"], name="stocks_hist_stock_i_0d6fd5_idx"
                    ),
                    models.Index(fields=["date"], name="stocks_hist_date_80b13a_idx"),
                ],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
