# Generated by Django 5.2.4 on 2025-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stock",
            name="stocks_stoc_market__e3b658_idx",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="market_cap_numeric",
        ),
        migrations.AddField(
            model_name="stock",
            name="return_10y",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="10年回报率 (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="return_1y",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="1年回报率 (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="return_3y",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="3年回报率 (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="return_5y",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="5年回报率 (%)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="market_cap",
            field=models.BigIntegerField(
                blank=True, help_text="可用于排序的数值型市值", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["-market_cap", "is_active"],
                name="stocks_stoc_market__2e6518_idx",
            ),
        ),
    ]
