# Generated by Django 5.2.4 on 2025-08-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="market_cap",
            field=models.BigIntegerField(
                blank=True, db_index=True, help_text="公司市值(纯数字)", null=True
            ),
        ),
    ]
