# Generated by Django 5.2.4 on 2025-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_stock_exchange_historicalprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="chinese_keywords",
            field=models.CharField(
                blank=True, help_text="逗号分隔的中文名称、别名或关键词", max_length=255
            ),
        ),
    ]
