# Generated by Django 5.2.4 on 2025-08-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_alter_stock_market_cap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="listed_date",
            new_name="ipo",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="delisted_date",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="eps",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="pe_ratio",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="test_issue",
        ),
        migrations.AddField(
            model_name="stock",
            name="country",
            field=models.CharField(
                blank=True, help_text="公司所在国家", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="finnhub_industry",
            field=models.CharField(
                blank=True, help_text="Finnhub行业分类", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="phone",
            field=models.CharField(
                blank=True, help_text="公司电话", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="change",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="相比前一天的价格变化",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="change_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="价格变化的百分比",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="exchange",
            field=models.CharField(db_index=True, help_text="交易所", max_length=50),
        ),
        migrations.AlterField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="是否为活跃交易的股票"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="此条记录在数据库中最后一次更新的时间"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="market_cap",
            field=models.BigIntegerField(
                blank=True, db_index=True, help_text="公司市值(完整数值)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(help_text="公司名称", max_length=255),
        ),
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="最新价格",
                max_digits=10,
                null=True,
            ),
        ),
    ]
