# Generated by Django 5.2.4 on 2025-08-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_rename_listed_date_stock_ipo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprice",
            name="high",
        ),
        migrations.RemoveField(
            model_name="historicalprice",
            name="low",
        ),
        migrations.RemoveField(
            model_name="historicalprice",
            name="open",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="change",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="change_percent",
        ),
        migrations.AlterField(
            model_name="stock",
            name="chinese_keywords",
            field=models.CharField(
                blank=True, help_text="中文关键词", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="是否活跃交易"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="数据库记录最后更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="最新收盘价格",
                max_digits=10,
                null=True,
            ),
        ),
    ]
