# Generated by Django 5.2.4 on 2025-08-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_remove_historicalprice_high_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="chinese_keywords",
            field=models.CharField(
                blank=True, help_text="中文关键词，用于搜索", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="是否为活跃交易的股票"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="此条记录在数据库中最后一次更新的时间"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="最新收盘价",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["-market_cap", "is_active"],
                name="stocks_stoc_market__2e6518_idx",
            ),
        ),
    ]
